services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb+srv://vnd:vnd123@cluster0.5akck.mongodb.net
      - PORT=5003
      - JWT_SECRET=secret
      - JWT_EXPIRE=30d
      - NODE_ENV=development
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:5003/api
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
